# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweetData',
            fields=[
                ('userName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tweettime', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=141)),
            ],
        ),
    ]
