# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_tweetdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdata',
            name='tweettime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
