# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20170816_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdata',
            name='msgID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweetdata',
            name='userName',
            field=models.CharField(max_length=100),
        ),
    ]
