# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 04:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20170816_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdata',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 8, 17, 4, 37, 29, 189670, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
